Creation of ndarray

Write python code to create 3d array in different ways with 15 elements.
Array Creation:
a. Create a 4D NumPy array containing the first 12 positive integers as arr1. b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1. 3. Find all attributes of array1 and array2 4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

Array Slicing and Indexing:

a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

b.Basic Indexing: - Print the element at index 3 of arr1. - Print the element at row 2, column 1 of arr2

c. Array Slicing: - Print the first five elements of arr1. - Print the subarray of arr2 consisting of the last two rows and the first two columns. - Print every second element starting from index 1 up to index 7 of arr1.

Data Type Manipulation

a. Creating Arrays with Specific Data Types: - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.

b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. - Convert the int_array to an array with data type float32. Print the result.

Generating Random Numbers:

Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

Apply descriptive statistics for rand_matrix.

Analyze the Data:

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

Describe the data using numpy array. Measure the following:

How many employees are getting more less than 50000?

Is it following Normal Distribution?

What is the median salary?

What is the range of salaries for this company?

Find the salaries between average salary and 75% of salaries?

How many employees are getting less than 25 % of salaries ?

Creation of ndarray

Write python code to create 3d array in different ways with 15 elements. Array Creation: a. Create a 4D NumPy array containing the first 12 positive integers as arr1. b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1. 3. Find all attributes of array1 and array2 4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

In [1]:
import numpy as np

In [150]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15], ndmin = 3)

In [151]:
arr1

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [152]:
arr1.reshape(1,3,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [153]:
arr2 = np.arange(1,16)

In [154]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [155]:
arr2.reshape(3,1,5)

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]]])

a. Create a 4D NumPy array containing the first 12 positive integers as arr1. 

In [156]:
arr1 = np.arange(1,13)

In [157]:
arr1.reshape(1,1,3,4)

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]])

In [158]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12], ndmin = 4)

In [159]:
arr1

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

. b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1. 3. Find all attributes of array1 and array2 4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

In [160]:
array2 = np.random.rand(20)

In [161]:
array2

array([0.79333125, 0.16022359, 0.97235536, 0.17796911, 0.98979813,
       0.42139454, 0.34277313, 0.29550056, 0.29833373, 0.0090313 ,
       0.54310292, 0.18708015, 0.75542758, 0.65373244, 0.53678792,
       0.76996718, 0.00941925, 0.15116268, 0.6263889 , 0.07241469])

## Atrributes

In [162]:
arr1.dtype

dtype('int32')

In [163]:
arr1.ndim

4

In [164]:
arr1.size

12

In [165]:
arr1.nbytes

48

In [166]:
arr1.itemsize

4

In [167]:
array2.dtype

dtype('float64')

In [168]:
array2.ndim

1

In [169]:
array2.size

20

In [170]:
array2.nbytes

160

In [171]:
array2.itemsize

8

### descriptive statistics

In [172]:
arr1

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

In [173]:
array2

array([0.79333125, 0.16022359, 0.97235536, 0.17796911, 0.98979813,
       0.42139454, 0.34277313, 0.29550056, 0.29833373, 0.0090313 ,
       0.54310292, 0.18708015, 0.75542758, 0.65373244, 0.53678792,
       0.76996718, 0.00941925, 0.15116268, 0.6263889 , 0.07241469])

In [174]:
# mean of arr1 and array 2
np.mean(arr1)


6.5

In [175]:
np.mean(array2)

0.43830971960213755

In [176]:
# median of arr1 and array2
np.median(arr1)

6.5

In [177]:
np.median(array2)

0.38208383621787434

In [178]:
# measure of spread 


In [179]:
# range of arr1
range1 = np.max(arr1) - np.min(arr1)
range1

11

In [180]:
# range of array2
range2 =  np.max(array2) - np.min(array2)
range2

0.9807668310913348

In [181]:
# variance of arr1
np.var(arr1)

11.916666666666666

In [182]:
# variance of array2
np.var(array2)

0.0935295663595512

In [183]:
# standard deviation of arr1
np.std(arr1)

3.452052529534663

In [184]:
# standard deviation of array2
np.std(array2)

0.3058260393745948

In [141]:
# IQR of arr1
q3_1 = np.percentile(arr1,75)
q1_1 = np.percentile(arr1,25)
IQR1 = q3_1 - q1_1
IQR1

40.0

In [185]:
# IQR of array2 
q3_2 = np.percentile(array2,75)
q1_2 = np.percentile(array2,25)
IQR2 = q3_2 - q1_2
IQR2

0.5056234950631148

In [187]:
# to find outlier of arr1
lower_limit = q1_1 - (1.5 * IQR1)
upper_limit = q3_1 + (1.5 * IQR1)


In [188]:
arr1>upper_limit

array([[[[False, False, False, False, False, False, False, False,
          False, False, False, False]]]])

In [189]:
arr1

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

In [190]:
## no outliers

In [191]:
arr1<lower_limit

array([[[[False, False, False, False, False, False, False, False,
          False, False, False, False]]]])

In [192]:
# to find outlier of array2
lower_limit_2 = q1_2 - (1.5 * IQR1)
upper_limit_2 = q3_2 + (1.5 * IQR1)

In [193]:
array2

array([0.79333125, 0.16022359, 0.97235536, 0.17796911, 0.98979813,
       0.42139454, 0.34277313, 0.29550056, 0.29833373, 0.0090313 ,
       0.54310292, 0.18708015, 0.75542758, 0.65373244, 0.53678792,
       0.76996718, 0.00941925, 0.15116268, 0.6263889 , 0.07241469])

In [194]:
array2>upper_limit_2

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [195]:
array2<lower_limit_2

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [196]:
# from above no outliers in array2

Array Slicing and Indexing:

a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

b.Basic Indexing: - Print the element at index 3 of arr1. - Print the element at row 2, column 1 of arr2

c. Array Slicing: - Print the first five elements of arr1. - Print the subarray of arr2 consisting of the last two rows and the first two columns. - Print every second element starting from index 1 up to index 7 of arr1.

In [197]:
arr1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])

In [198]:
arr2 = np.array( [[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [199]:
arr1[3]

73

In [200]:
arr2[1][0]

3

In [201]:
arr1[:5]

array([ 0, 11, 26, 73, 42])

In [202]:
arr2[1:,0:2]

array([[3, 4],
       [6, 7]])

In [203]:
arr1[1:8:2]

array([11, 73, 51, 77])

Data Type Manipulation

a. Creating Arrays with Specific Data Types: - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.

b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. - Convert the int_array to an array with data type float32. Print the result.

In [204]:
int_array = np.array([1, 2, 3, 4, 5],dtype="int16")

In [205]:
int_array.dtype

dtype('int16')

In [206]:
float_array = np.array([0.1, 0.2, 0.3, 0.4, 0.5],dtype ="float32")

In [207]:
float_array.dtype

dtype('float32')

In [208]:
float_conversion = np.array([0.1, 0.2, 0.3, 0.4, 0.5],dtype = "int32")
float_conversion.dtype

dtype('int32')

In [209]:
float_conversion

array([0, 0, 0, 0, 0])

In [210]:
int_conversion =  np.array([1, 2, 3, 4, 5],dtype="float32")
int_conversion.dtype

dtype('float32')

In [211]:
int_conversion

array([1., 2., 3., 4., 5.], dtype=float32)

Generating Random Numbers:

Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

Apply descriptive statistics for rand_matrix.

In [212]:
np.random.randint(0,100,10)

array([ 6, 32, 20, 23, 68, 92, 84, 88,  2, 83])

In [213]:
np.random.uniform(-1,1,5)

array([ 0.86745162, -0.26258416,  0.72682466, -0.37066702, -0.35269213])

In [217]:
rand_matrix = np.random.randint(50,101,16).reshape(4,4)
rand_matrix

array([[100,  81,  56,  59],
       [ 90,  83,  85,  78],
       [ 72,  94,  67,  55],
       [ 98,  90,  57,  60]])

descripitve statistics

In [218]:
# mean 
np.mean(rand_matrix)

76.5625

In [219]:
# median
np.median(rand_matrix)

79.5

In [220]:
# range 
range1 = np.max(rand_matrix) - np.min(rand_matrix)
range1

45

In [221]:
# variance
np.var(rand_matrix)

235.87109375

In [222]:
# standard deviation
np.std(rand_matrix)

15.358095381589477

In [130]:
# IQR

In [223]:
q3= np.percentile(rand_matrix,75)
q1 = np.percentile(rand_matrix,25)
IQR = q3-q1
IQR

30.25

In [224]:
# to find outlier
lower_limit = q1 - (1.5 * IQR)
upper_limit = q3 + (1.5 * IQR)

In [225]:
rand_matrix

array([[100,  81,  56,  59],
       [ 90,  83,  85,  78],
       [ 72,  94,  67,  55],
       [ 98,  90,  57,  60]])

In [226]:
rand_matrix>upper_limit

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [227]:
rand_matrix<lower_limit

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [136]:
# no outliers

Analyze the Data:

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

Describe the data using numpy array. Measure the following:

How many employees are getting more less than 50000?

Is it following Normal Distribution?

What is the median salary?

What is the range of salaries for this company?

Find the salaries between average salary and 75% of salaries?

How many employees are getting less than 25 % of salaries ?

In [232]:
salaries = np.array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638])

In [229]:
salaries[salaries<50000]

array([31250, 39828, 41671, 34225, 32199])

In [230]:
# 5 employess are getting more less than 50000

In [237]:
# mean 
m = np.mean(salaries)
m

166169.16666666666

In [238]:
np.median(salaries)

61699.5

In [241]:
std1 = np.std(salaries)
std1

547678.585700353

In [243]:
range1 = m-std1
range1

-381509.4190336864

In [244]:
range2 = m+std1
range2

713847.7523670197

In [245]:
salaries[salaries<range1]

array([], dtype=int32)

In [258]:
s_68 = salaries[salaries<range2] # 68% of data
s_68

array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828,
       60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833,
       50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947,
       55723, 64557])

In [259]:
len(s_68)

29

In [247]:
range3 = m - (2 * std1)
range3

-929188.0047340394

In [249]:
range4 = m + (2 * std1)
range4

1261526.3380673728

In [254]:
s_95 = salaries[salaries<range4]
s_95

array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828,
       60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833,
       50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947,
       55723, 64557])

In [255]:
len(salaries)

30

In [256]:
len(s_95)

29

In [260]:
# out of 30, 29 elements in 68 and 95 percentage so data is  in normal distribution 

In [261]:
q3= np.percentile(salaries,75)
q1 = np.percentile(salaries,25)
IQR = q3-q1
IQR

31533.25

In [262]:
lower_limit = q1 - (1.5 * IQR)
upper_limit = q3 + (1.5 * IQR)

In [265]:
salaries[salaries > upper_limit]

array([3113638])

In [266]:
salaries[salaries < lower_limit]

array([], dtype=int32)

In [267]:
# only one outlier -- 31533.25

In [268]:
# median 
np.median(salaries)

61699.5

In [270]:
# range
range_salaries = np.max(salaries) - np.min(salaries)
range_salaries

3082388

In [273]:
# avearge = mean
avg = np.mean(salaries)
avg

166169.16666666666

In [274]:
q3

84496.5

In [282]:
salaries[(salaries > avg)]

array([3113638])

In [286]:
salaries[(salaries >=q3)] # the salaries between average salary and 75% of salaries.

array([  87877,   85051,   94868,   98446,   99658,   89224,   90947,
       3113638])

In [285]:
len(salaries[(salaries >=q3)])

8

In [287]:
# 7 salaries 

In [289]:
q1

52963.25

In [288]:
salaries[salaries<q1]

array([52453, 31250, 39828, 41671, 51428, 50477, 34225, 32199])

In [290]:
len(salaries[salaries<q1])

8

In [ ]:
"8" employees are getting less than 25 % of salaries.