clean the data(outlier,missing values,type conversion)

What is the mean value of sepal length

sort the sepal width in ascending order.

apply all statistical measures on sepal width and length

after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values


In [41]:
import numpy as np

In [42]:
data = np.genfromtxt(r"C:\Users\mm732\Downloads\Iris_clean_-_Copy.csv",dtype = "float16",delimiter = ",")

In [43]:
data

array([[      nan,       nan,       nan,       nan],
       [5.102e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.699e+00, 3.199e+00, 1.300e+00, 2.000e-01],
       [4.602e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.398e+00,       nan, 1.700e+00, 3.999e-01],
       [4.602e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.398e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.100e+00,       nan, 9.998e-02],
       [5.398e+00, 3.699e+00, 1.500e+00, 2.000e-01],
       [4.801e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.801e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.301e+00, 3.000e+00, 1.100e+00, 9.998e-02],
       [5.801e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.699e+00, 4.398e+00, 1.500e+00, 3.999e-01],
       [5.041e+01,       nan, 1.300e+00, 3.999e-01],
       [5.102e+00, 3.500e+00, 1.400e+00, 3.000

In [44]:
sepal_length = data[1:,0:1]

In [45]:
sepal_length

array([[  5.1],
       [  4.9],
       [  4.7],
       [  4.6],
       [ 50. ],
       [  5.4],
       [  4.6],
       [  5. ],
       [  4.4],
       [  4.9],
       [  5.4],
       [  4.8],
       [  4.8],
       [  4.3],
       [  5.8],
       [  5.7],
       [ 50.4],
       [  5.1],
       [  5.7],
       [  5.1],
       [  5.4],
       [  5.1],
       [  4.6],
       [  5.1],
       [  4.8],
       [  5. ],
       [  5. ],
       [  5.2],
       [  5.2],
       [  4.7],
       [  4.8],
       [  5.4],
       [  5.2],
       [  5.5],
       [  4.9],
       [  5. ],
       [  5.5],
       [  4.9],
       [  4.4],
       [  5.1],
       [  5. ],
       [  4.5],
       [  4.4],
       [  5. ],
       [  5.1],
       [  4.8],
       [  5.1],
       [  4.6],
       [  5.3],
       [  5. ],
       [  7. ],
       [  6.4],
       [  6.9],
       [  5.5],
       [  6.5],
       [  5.7],
       [116.3],
       [  4.9],
       [  6.6],
       [  5.2],
       [  5. ],
       [  5.9],
       [

In [46]:
np.where(sepal_length>10) # outliers

(array([  4,  16,  56, 129], dtype=int64), array([0, 0, 0, 0], dtype=int64))

In [47]:
sepal_length = np.where(sepal_length>10,np.nanmedian(sepal_length),sepal_length)  #  outliers conversion

In [48]:
sepal_length

array([[5.1],
       [4.9],
       [4.7],
       [4.6],
       [5.8],
       [5.4],
       [4.6],
       [5. ],
       [4.4],
       [4.9],
       [5.4],
       [4.8],
       [4.8],
       [4.3],
       [5.8],
       [5.7],
       [5.8],
       [5.1],
       [5.7],
       [5.1],
       [5.4],
       [5.1],
       [4.6],
       [5.1],
       [4.8],
       [5. ],
       [5. ],
       [5.2],
       [5.2],
       [4.7],
       [4.8],
       [5.4],
       [5.2],
       [5.5],
       [4.9],
       [5. ],
       [5.5],
       [4.9],
       [4.4],
       [5.1],
       [5. ],
       [4.5],
       [4.4],
       [5. ],
       [5.1],
       [4.8],
       [5.1],
       [4.6],
       [5.3],
       [5. ],
       [7. ],
       [6.4],
       [6.9],
       [5.5],
       [6.5],
       [5.7],
       [5.8],
       [4.9],
       [6.6],
       [5.2],
       [5. ],
       [5.9],
       [6. ],
       [6.1],
       [5.6],
       [6.7],
       [5.6],
       [5.8],
       [6.2],
       [5.6],
       [5.9],
      

In [49]:
sepal_length = np.where(np.isnan(sepal_length),np.nanmean(sepal_length),sepal_length)  # conversion of missing values

In [50]:
sepal_length

array([[5.1 ],
       [4.9 ],
       [4.7 ],
       [4.6 ],
       [5.8 ],
       [5.4 ],
       [4.6 ],
       [5.  ],
       [4.4 ],
       [4.9 ],
       [5.4 ],
       [4.8 ],
       [4.8 ],
       [4.3 ],
       [5.8 ],
       [5.7 ],
       [5.8 ],
       [5.1 ],
       [5.7 ],
       [5.1 ],
       [5.4 ],
       [5.1 ],
       [4.6 ],
       [5.1 ],
       [4.8 ],
       [5.  ],
       [5.  ],
       [5.2 ],
       [5.2 ],
       [4.7 ],
       [4.8 ],
       [5.4 ],
       [5.2 ],
       [5.5 ],
       [4.9 ],
       [5.  ],
       [5.5 ],
       [4.9 ],
       [4.4 ],
       [5.1 ],
       [5.  ],
       [4.5 ],
       [4.4 ],
       [5.  ],
       [5.1 ],
       [4.8 ],
       [5.1 ],
       [4.6 ],
       [5.3 ],
       [5.  ],
       [7.  ],
       [6.4 ],
       [6.9 ],
       [5.5 ],
       [6.5 ],
       [5.7 ],
       [5.8 ],
       [4.9 ],
       [6.6 ],
       [5.2 ],
       [5.  ],
       [5.9 ],
       [6.  ],
       [6.1 ],
       [5.6 ],
       [6.7 ],
       [5.

In [51]:
sepal_width = data[1:,1:2]

In [52]:
sepal_width

array([[  3.5],
       [  3. ],
       [  3.2],
       [  3.1],
       [  3.6],
       [  nan],
       [  3.4],
       [  3.4],
       [  2.9],
       [  3.1],
       [  3.7],
       [  3.4],
       [130. ],
       [  3. ],
       [  4. ],
       [  4.4],
       [  nan],
       [  3.5],
       [  3.8],
       [  3.8],
       [  3.4],
       [  3.7],
       [  3.6],
       [  3.3],
       [  3.4],
       [  3. ],
       [ 34. ],
       [  3.5],
       [  3.4],
       [  3.2],
       [  3.1],
       [  3.4],
       [  4.1],
       [  4.2],
       [  3.1],
       [  3.2],
       [  3.5],
       [  3.1],
       [  3. ],
       [  3.4],
       [  3.5],
       [  2.3],
       [  3.2],
       [  3.5],
       [  3.8],
       [  3. ],
       [  3.8],
       [  3.2],
       [  3.7],
       [  3.3],
       [  3.2],
       [  3.2],
       [  nan],
       [  2.3],
       [  2.8],
       [  2.8],
       [  3.3],
       [  2.4],
       [  2.9],
       [  2.7],
       [  2. ],
       [  3. ],
       [

In [53]:
np.where(sepal_width>5) # outliers

(array([12, 26, 92], dtype=int64), array([0, 0, 0], dtype=int64))

In [54]:
sepal_width = np.where(sepal_width>5,np.nanmedian(sepal_width),sepal_width) # conversion of outliers  

In [55]:
sepal_width

array([[3.5],
       [3. ],
       [3.2],
       [3.1],
       [3.6],
       [nan],
       [3.4],
       [3.4],
       [2.9],
       [3.1],
       [3.7],
       [3.4],
       [3. ],
       [3. ],
       [4. ],
       [4.4],
       [nan],
       [3.5],
       [3.8],
       [3.8],
       [3.4],
       [3.7],
       [3.6],
       [3.3],
       [3.4],
       [3. ],
       [3. ],
       [3.5],
       [3.4],
       [3.2],
       [3.1],
       [3.4],
       [4.1],
       [4.2],
       [3.1],
       [3.2],
       [3.5],
       [3.1],
       [3. ],
       [3.4],
       [3.5],
       [2.3],
       [3.2],
       [3.5],
       [3.8],
       [3. ],
       [3.8],
       [3.2],
       [3.7],
       [3.3],
       [3.2],
       [3.2],
       [nan],
       [2.3],
       [2.8],
       [2.8],
       [3.3],
       [2.4],
       [2.9],
       [2.7],
       [2. ],
       [3. ],
       [2.2],
       [2.9],
       [2.9],
       [3.1],
       [3. ],
       [2.7],
       [2.2],
       [2.5],
       [3.2],
      

In [56]:
sepal_width = np.where(np.isnan(sepal_width),np.nanmean(sepal_width),sepal_width)  # conversion of missing values 

In [57]:
sepal_width

array([[3.5 ],
       [3.  ],
       [3.2 ],
       [3.1 ],
       [3.6 ],
       [3.03],
       [3.4 ],
       [3.4 ],
       [2.9 ],
       [3.1 ],
       [3.7 ],
       [3.4 ],
       [3.  ],
       [3.  ],
       [4.  ],
       [4.4 ],
       [3.03],
       [3.5 ],
       [3.8 ],
       [3.8 ],
       [3.4 ],
       [3.7 ],
       [3.6 ],
       [3.3 ],
       [3.4 ],
       [3.  ],
       [3.  ],
       [3.5 ],
       [3.4 ],
       [3.2 ],
       [3.1 ],
       [3.4 ],
       [4.1 ],
       [4.2 ],
       [3.1 ],
       [3.2 ],
       [3.5 ],
       [3.1 ],
       [3.  ],
       [3.4 ],
       [3.5 ],
       [2.3 ],
       [3.2 ],
       [3.5 ],
       [3.8 ],
       [3.  ],
       [3.8 ],
       [3.2 ],
       [3.7 ],
       [3.3 ],
       [3.2 ],
       [3.2 ],
       [3.03],
       [2.3 ],
       [2.8 ],
       [2.8 ],
       [3.3 ],
       [2.4 ],
       [2.9 ],
       [2.7 ],
       [2.  ],
       [3.  ],
       [2.2 ],
       [2.9 ],
       [2.9 ],
       [3.1 ],
       [3.

In [58]:
petal_length = data[1:,2:3]

In [60]:
petal_length

array([[ 1.4],
       [ 1.4],
       [ 1.3],
       [ 1.5],
       [ 1.4],
       [ 1.7],
       [ 1.4],
       [ 1.5],
       [ 1.4],
       [ nan],
       [ 1.5],
       [ 1.6],
       [ 1.4],
       [ 1.1],
       [ 1.2],
       [ 1.5],
       [ 1.3],
       [ 1.4],
       [ 1.7],
       [ 1.5],
       [ 1.7],
       [ 1.5],
       [ 1. ],
       [ 1.7],
       [ 1.9],
       [ 1.6],
       [ 1.6],
       [ 1.5],
       [ 1.4],
       [ 1.6],
       [ 1.6],
       [ 1.5],
       [ 1.5],
       [ 1.4],
       [ 1.5],
       [ 1.2],
       [ 1.3],
       [ 1.5],
       [ 1.3],
       [ 1.5],
       [ 1.3],
       [13. ],
       [ 1.3],
       [ 1.6],
       [ 1.9],
       [ 1.4],
       [ 1.6],
       [ 1.4],
       [ 1.5],
       [ 1.4],
       [ 4.7],
       [ 4.5],
       [ 4.9],
       [ 4. ],
       [ 4.6],
       [ 4.5],
       [ 4.7],
       [ 3.3],
       [ 4.6],
       [ 3.9],
       [ 3.5],
       [ 4.2],
       [ 4. ],
       [ 4.7],
       [ 3.6],
       [ 4.4],
       [ 4

In [61]:
np.where(petal_length>10) # outliers

(array([41, 80], dtype=int64), array([0, 0], dtype=int64))

In [62]:
petal_length = np.where(petal_length>10,np.nanmedian(petal_length),petal_length)  # conversion of outliers

In [63]:
petal_length

array([[1.4],
       [1.4],
       [1.3],
       [1.5],
       [1.4],
       [1.7],
       [1.4],
       [1.5],
       [1.4],
       [nan],
       [1.5],
       [1.6],
       [1.4],
       [1.1],
       [1.2],
       [1.5],
       [1.3],
       [1.4],
       [1.7],
       [1.5],
       [1.7],
       [1.5],
       [1. ],
       [1.7],
       [1.9],
       [1.6],
       [1.6],
       [1.5],
       [1.4],
       [1.6],
       [1.6],
       [1.5],
       [1.5],
       [1.4],
       [1.5],
       [1.2],
       [1.3],
       [1.5],
       [1.3],
       [1.5],
       [1.3],
       [4.5],
       [1.3],
       [1.6],
       [1.9],
       [1.4],
       [1.6],
       [1.4],
       [1.5],
       [1.4],
       [4.7],
       [4.5],
       [4.9],
       [4. ],
       [4.6],
       [4.5],
       [4.7],
       [3.3],
       [4.6],
       [3.9],
       [3.5],
       [4.2],
       [4. ],
       [4.7],
       [3.6],
       [4.4],
       [4.5],
       [4.1],
       [4.5],
       [3.9],
       [4.8],
      

In [64]:
petal_length = np.where(np.isnan(petal_length),np.nanmean(petal_length),petal_length)

In [65]:
petal_length

array([[1.4  ],
       [1.4  ],
       [1.3  ],
       [1.5  ],
       [1.4  ],
       [1.7  ],
       [1.4  ],
       [1.5  ],
       [1.4  ],
       [3.912],
       [1.5  ],
       [1.6  ],
       [1.4  ],
       [1.1  ],
       [1.2  ],
       [1.5  ],
       [1.3  ],
       [1.4  ],
       [1.7  ],
       [1.5  ],
       [1.7  ],
       [1.5  ],
       [1.   ],
       [1.7  ],
       [1.9  ],
       [1.6  ],
       [1.6  ],
       [1.5  ],
       [1.4  ],
       [1.6  ],
       [1.6  ],
       [1.5  ],
       [1.5  ],
       [1.4  ],
       [1.5  ],
       [1.2  ],
       [1.3  ],
       [1.5  ],
       [1.3  ],
       [1.5  ],
       [1.3  ],
       [4.5  ],
       [1.3  ],
       [1.6  ],
       [1.9  ],
       [1.4  ],
       [1.6  ],
       [1.4  ],
       [1.5  ],
       [1.4  ],
       [4.7  ],
       [4.5  ],
       [4.9  ],
       [4.   ],
       [4.6  ],
       [4.5  ],
       [4.7  ],
       [3.3  ],
       [4.6  ],
       [3.9  ],
       [3.5  ],
       [4.2  ],
       [

In [77]:
petal_width = data[1:,3:]

In [78]:
petal_width

array([[2.000e-01],
       [2.000e-01],
       [2.000e-01],
       [1.020e+01],
       [2.000e-01],
       [3.999e-01],
       [3.000e-01],
       [2.000e-01],
       [2.000e-01],
       [9.998e-02],
       [2.000e-01],
       [2.000e-01],
       [1.010e+01],
       [9.998e-02],
       [2.000e-01],
       [3.999e-01],
       [3.999e-01],
       [3.000e-01],
       [3.000e-01],
       [3.000e-01],
       [2.000e-01],
       [3.999e-01],
       [2.000e-01],
       [5.000e-01],
       [2.000e-01],
       [2.000e-01],
       [3.999e-01],
       [2.000e-01],
       [1.102e+02],
       [2.000e-01],
       [2.000e-01],
       [3.999e-01],
       [9.998e-02],
       [2.000e-01],
       [9.998e-02],
       [2.000e-01],
       [2.000e-01],
       [9.998e-02],
       [2.000e-01],
       [2.000e-01],
       [3.000e-01],
       [3.000e-01],
       [2.000e-01],
       [6.001e-01],
       [3.999e-01],
       [3.000e-01],
       [2.000e-01],
       [2.000e-01],
       [2.000e-01],
       [2.000e-01],


In [79]:
np.where(petal_width>3)

(array([ 3, 12, 28, 57, 98], dtype=int64), array([0, 0, 0, 0, 0], dtype=int64))

In [80]:
petal_width =  np.where(petal_width>3,np.nanmedian(petal_width),petal_width)

In [76]:
petal_width

array([[0.2],
       [0.2],
       [0.2],
       [1.5],
       [0.2],
       [0.4],
       [0.3],
       [0.2],
       [0.2],
       [0.1],
       [0.2],
       [0.2],
       [1.5],
       [0.1],
       [0.2],
       [0.4],
       [0.4],
       [0.3],
       [0.3],
       [0.3],
       [0.2],
       [0.4],
       [0.2],
       [0.5],
       [0.2],
       [0.2],
       [0.4],
       [0.2],
       [1.5],
       [0.2],
       [0.2],
       [0.4],
       [0.1],
       [0.2],
       [0.1],
       [0.2],
       [0.2],
       [0.1],
       [0.2],
       [0.2],
       [0.3],
       [0.3],
       [0.2],
       [0.6],
       [0.4],
       [0.3],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [1.4],
       [1.5],
       [1.5],
       [1.3],
       [1.5],
       [1.3],
       [1.6],
       [1.5],
       [1.3],
       [1.4],
       [1. ],
       [1.5],
       [1. ],
       [1.4],
       [1.3],
       [1.4],
       [1.5],
       [1. ],
       [1.5],
       [1.1],
       [1.8],
      

2.What is the mean value of sepal length

In [81]:
np.mean(sepal_length)

5.87

3.sort the sepal width in ascending order.

In [82]:
np.sort(sepal_width)

array([[3.5 ],
       [3.  ],
       [3.2 ],
       [3.1 ],
       [3.6 ],
       [3.03],
       [3.4 ],
       [3.4 ],
       [2.9 ],
       [3.1 ],
       [3.7 ],
       [3.4 ],
       [3.  ],
       [3.  ],
       [4.  ],
       [4.4 ],
       [3.03],
       [3.5 ],
       [3.8 ],
       [3.8 ],
       [3.4 ],
       [3.7 ],
       [3.6 ],
       [3.3 ],
       [3.4 ],
       [3.  ],
       [3.  ],
       [3.5 ],
       [3.4 ],
       [3.2 ],
       [3.1 ],
       [3.4 ],
       [4.1 ],
       [4.2 ],
       [3.1 ],
       [3.2 ],
       [3.5 ],
       [3.1 ],
       [3.  ],
       [3.4 ],
       [3.5 ],
       [2.3 ],
       [3.2 ],
       [3.5 ],
       [3.8 ],
       [3.  ],
       [3.8 ],
       [3.2 ],
       [3.7 ],
       [3.3 ],
       [3.2 ],
       [3.2 ],
       [3.03],
       [2.3 ],
       [2.8 ],
       [2.8 ],
       [3.3 ],
       [2.4 ],
       [2.9 ],
       [2.7 ],
       [2.  ],
       [3.  ],
       [2.2 ],
       [2.9 ],
       [2.9 ],
       [3.1 ],
       [3.

4.apply all statistical measures on sepal width and length

In [83]:
# mean
np.mean(sepal_width) # mean of sepal width

3.03

In [84]:
np.mean(sepal_length) # mean of sepal length

5.87

In [85]:
# median'
np.median(sepal_length) # median of sepal_length

5.8

In [86]:
np.median(sepal_width)  # median of sepal_length

3.0

In [87]:
# variance 
np.var(sepal_length)  # variance of sepal_length

0.653

In [88]:
np.var(sepal_width)   # variance of sepal_width

0.1683

In [89]:
# standard_devition 
np.std(sepal_length)   # standard_devition of sepal_length

0.808

In [90]:
np.std(sepal_width)  # standard_devition of sepal_width

0.4104

In [106]:
q3 = np.quantile(sepal_length,0.75)

In [107]:
q3

6.3984375

In [108]:
q1 = np.quantile(sepal_length,0.25)

In [109]:
q1

5.19921875

In [110]:
IQR = q3-q1

In [111]:
IQR  # IOR of sepal_length

1.19921875

In [114]:
IQR1 = np.quantile(sepal_width,0.75) - np.quantile(sepal_width,0.25)

In [115]:
IQR1 # IQR of sepal_width

0.3984375

In [116]:
# range
range1 = np.max(sepal_width) - np.min(sepal_width)

In [117]:
range1 # range of sepal_width

2.398

In [118]:
range2 = np.max(sepal_length) - np.min(sepal_length)

In [119]:
range2 # range of sepal_length

3.398

after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [121]:
np.savetxt("sepal_length_cleaned_iris.txt",sepal_length)

In [122]:
np.loadtxt("sepal_length_cleaned_iris.txt")

array([5.1015625 , 4.8984375 , 4.69921875, 4.6015625 , 5.80078125,
       5.3984375 , 4.6015625 , 5.        , 4.3984375 , 4.8984375 ,
       5.3984375 , 4.80078125, 4.80078125, 4.30078125, 5.80078125,
       5.69921875, 5.80078125, 5.1015625 , 5.69921875, 5.1015625 ,
       5.3984375 , 5.1015625 , 4.6015625 , 5.1015625 , 4.80078125,
       5.        , 5.        , 5.19921875, 5.19921875, 4.69921875,
       4.80078125, 5.3984375 , 5.19921875, 5.5       , 4.8984375 ,
       5.        , 5.5       , 4.8984375 , 4.3984375 , 5.1015625 ,
       5.        , 4.5       , 4.3984375 , 5.        , 5.1015625 ,
       4.80078125, 5.1015625 , 4.6015625 , 5.30078125, 5.        ,
       7.        , 6.3984375 , 6.8984375 , 5.5       , 6.5       ,
       5.69921875, 5.80078125, 4.8984375 , 6.6015625 , 5.19921875,
       5.        , 5.8984375 , 6.        , 6.1015625 , 5.6015625 ,
       6.69921875, 5.6015625 , 5.80078125, 6.19921875, 5.6015625 ,
       5.8984375 , 6.1015625 , 6.30078125, 6.1015625 , 6.39843

In [127]:
np.savetxt("sepal_width_cleaned_iris.txt",sepal_width)

In [128]:
np.loadtxt("sepal_width_cleaned_iris.txt")

array([3.5       , 3.        , 3.19921875, 3.09960938, 3.59960938,
       3.02929688, 3.40039062, 3.40039062, 2.90039062, 3.09960938,
       3.69921875, 3.40039062, 3.        , 3.        , 4.        ,
       4.3984375 , 3.02929688, 3.5       , 3.80078125, 3.80078125,
       3.40039062, 3.69921875, 3.59960938, 3.30078125, 3.40039062,
       3.        , 3.        , 3.5       , 3.40039062, 3.19921875,
       3.09960938, 3.40039062, 4.1015625 , 4.19921875, 3.09960938,
       3.19921875, 3.5       , 3.09960938, 3.        , 3.40039062,
       3.5       , 2.30078125, 3.19921875, 3.5       , 3.80078125,
       3.        , 3.80078125, 3.19921875, 3.69921875, 3.30078125,
       3.19921875, 3.19921875, 3.02929688, 2.30078125, 2.80078125,
       2.80078125, 3.30078125, 2.40039062, 2.90039062, 2.69921875,
       2.        , 3.        , 2.19921875, 2.90039062, 2.90039062,
       3.09960938, 3.        , 2.69921875, 2.19921875, 2.5       ,
       3.19921875, 2.80078125, 2.5       , 3.02929688, 2.90039

In [129]:
np.savetxt("petal_length_cleaned_iris.txt",petal_length)

In [130]:
np.loadtxt("petal_length_cleaned_iris.txt")

array([1.40039062, 1.40039062, 1.29980469, 1.5       , 1.40039062,
       1.70019531, 1.40039062, 1.5       , 1.40039062, 3.91210938,
       1.5       , 1.59960938, 1.40039062, 1.09960938, 1.20019531,
       1.5       , 1.29980469, 1.40039062, 1.70019531, 1.5       ,
       1.70019531, 1.5       , 1.        , 1.70019531, 1.90039062,
       1.59960938, 1.59960938, 1.5       , 1.40039062, 1.59960938,
       1.59960938, 1.5       , 1.5       , 1.40039062, 1.5       ,
       1.20019531, 1.29980469, 1.5       , 1.29980469, 1.5       ,
       1.29980469, 4.5       , 1.29980469, 1.59960938, 1.90039062,
       1.40039062, 1.59960938, 1.40039062, 1.5       , 1.40039062,
       4.69921875, 4.5       , 4.8984375 , 4.        , 4.6015625 ,
       4.5       , 4.69921875, 3.30078125, 4.6015625 , 3.90039062,
       3.5       , 4.19921875, 4.        , 4.69921875, 3.59960938,
       4.3984375 , 4.5       , 4.1015625 , 4.5       , 3.90039062,
       4.80078125, 4.        , 4.8984375 , 4.69921875, 4.30078

In [131]:
np.savetxt("petal_width_cleaned_iris.txt",petal_width)

In [132]:
np.loadtxt("petal_width_cleaned_iris.txt")

array([0.19995117, 0.19995117, 0.19995117, 1.5       , 0.19995117,
       0.39990234, 0.30004883, 0.19995117, 0.19995117, 0.09997559,
       0.19995117, 0.19995117, 1.5       , 0.09997559, 0.19995117,
       0.39990234, 0.39990234, 0.30004883, 0.30004883, 0.30004883,
       0.19995117, 0.39990234, 0.19995117, 0.5       , 0.19995117,
       0.19995117, 0.39990234, 0.19995117, 1.5       , 0.19995117,
       0.19995117, 0.39990234, 0.09997559, 0.19995117, 0.09997559,
       0.19995117, 0.19995117, 0.09997559, 0.19995117, 0.19995117,
       0.30004883, 0.30004883, 0.19995117, 0.60009766, 0.39990234,
       0.30004883, 0.19995117, 0.19995117, 0.19995117, 0.19995117,
       1.40039062, 1.5       , 1.5       , 1.29980469, 1.5       ,
       1.29980469, 1.59960938, 1.5       , 1.29980469, 1.40039062,
       1.        , 1.5       , 1.        , 1.40039062, 1.29980469,
       1.40039062, 1.5       , 1.        , 1.5       , 1.09960938,
       1.79980469, 1.29980469, 1.5       , 1.20019531, 1.29980

In [133]:
np.savez("iris.npz",sepal_length,sepal_width,petal_length,petal_width)

In [134]:
np.load("iris.npz")

NpzFile 'iris.npz' with keys: arr_0, arr_1, arr_2, arr_3